<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Glyph &middot; Taz Hair 14</title>
	<meta name="viewport" content="width=device-width">
	<style>

	body
	{
	margin: 0px;
	font: 18px Georgia, serif;
	line-height: 1.4;
	text-align: center;
	color: #000;
	}
	
	article
	{
	margin:0 auto;
	padding: 30px 15px;
	width: 354px;
	background-color: #FFF;
	}
	
	header
	{
	padding: 10px 0;
	border-top: 5px solid #000;
	border-bottom: 5px solid #000;
	}
	
	h1
	{
	font-size: 30px;
	margin: 0;
	}
	
	h2
	{
	font-size: 18px;
	font-weight: normal;
	margin: 0;
	}
	
	.illustration
	{
	display: block;
	margin: 10px 0;
	}
	
	.caption
	{
	border-top: 1px solid #000;
	border-bottom: 1px solid #000;
	padding: 8px 0;
	margin: 0;
	}

	.microreview
	{
	text-align: left;
	padding-bottom: 5px;
	border-bottom: 5px solid #000;
	}
	
    </style>
</head>
<body>
  <article>
  
    <header>
      <h1>Glyph</h1>
      <h2>A Tiny Tome on Typography</h2>
    </header>
    
    <img class="illustration" src="a-taz-hair-14.png" alt="Taz Hair 14 – 'a'." width="354" height="304">

    <p class="caption"><b>Taz Hair 14</b><br /> by Luc(as) de Groot</p>
    
    <div class="microreview">
      <p><b>Taz III</b>, by Dutch designer Luc(as) de Groot, takes the idea of a typographic superfamily to dizzying new heights. Available in a staggering fifteen weights with accompanying italics, it’s a true workhorse of a typeface. Designed as a space-saving headline family for newspapers, the hairlines are particularly pleasing. Use them large for a light and airy feel.</p>
      
      <p>getglyph.org/a/taz-hair-14</p>
    </div>
    
  </article>
</body>
</html>
